### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by Kamori** [sponges/GoMusicBot#4]
Hey @ducc, first want to say, thanks for putting all this work together! Its an awesome bot, and IMO an excellent starting point for someone wanting to learn Go and also expanding a discord bot as part of their project to learn.

I feel like a lot of design choices you made make it very easy for me to wrap my head around the code base, so its been pretty easy to expand on so far.

With that in mind, I submitted a PR #3 about a week ago with no response. And it made me curious if this project was still alive. I have more features I'd like to introduce into the bot for my own purposes, such as video caching for faster play time, and trivia because I'm on discord with a bunch of The Office nerds 😂 

Was curious if I should continue to submit PRs or just maintain a separate fork giving you credit?

**Comment by ducc** [comment]
Merged thank you :) I don't write discord bots anymore but I know this is passed around as a discordgo music bot starting point so any contributions are welcome. If I don't reply in the future please msg me spong#3338
